#!/bin/bash
function pre_prompt {
	newPWD="${PWD}"
	user=`whoami`
	host=$(echo -n $HOSTNAME | sed -e "s/[\.].*//")
	datenow=$(date "+%a, %Y-%m-%d")
	let promptsize=$(echo -n "┌($user@$host ddd, YYYY-mm-dd)(${PWD})┐" | wc -c | tr -d " ")
	let fillsize=${COLUMNS}-${promptsize}
	fill=""
	while [ "$fillsize" -gt "0" ]
	do
		fill="${fill}─"
		let fillsize=${fillsize}-1
	done
	if [ "$fillsize" -lt "0" ]
	then
		let cutt=3-${fillsize}
		newPWD="...$(echo -n $PWD | sed -e "s/\(^.\{$cutt\}\)\(.*\)/\2/")"
	fi
}

PROMPT_COMMAND=pre_prompt

case "$TERM" in
xterm|screen)
	PS1="$txtgrn┌─(${coldblue}\u@\h \$(date \"+%a, %Y-%m-%d\")$txtgrn)─\${fill}─($coldblue\${newPWD}$txtgrn)─┐\n$txtgrn└─($coldblue\$(date \"+%H:%M\") \$$txtgrn)─>$txtrst ";;
*)
	PS1="┌─(\u@\h \$(date \"+%a, %Y-%m-%d\"))─\${fill}─(\$newPWD)─┐\n└─(\$(date \"+%H:%M\") \$)─> ";;
esac

